[package]
name = "diceware"
version = "0.1.0"
authors = ["Yuval Langer <yuval.langer@gmail.com>"]
build = "build.rs"
license = "AGPL-3.0"
repository = "https://gitlab.com/yuvallanger/rusty-diceware"
description = ""


[dependencies]
rand = "0.3"
getopts = "0.2"
